RESULT		=	a.out
SOURCES		=	Atom.ml Molecule.ml Oxygen.ml Argon.ml Carbon.ml Cobalt.ml\
				Helium.ml Hydrogen.ml Iron.ml Neon.ml Radon.ml Titanium.ml\
				Nitrogen.ml Glucose.ml Ethanol.ml Carbon_dioxyde.ml Water.ml\
				Dinitrogen_oxide.ml TNT.ml Alkane.ml Ethane.ml Octane.ml\
				Methane.ml Reaction.ml main.ml
include OCamlMakefile